In [1]:
list = [10,20,30]

[i**2 for i in list]

[100, 400, 900]

In [2]:
names = [["John","Emily","Michael","Mary","Steven"],
         ["Maria","Juan","Javier","Natalia","Pilar"]]
print(names)

[['John', 'Emily', 'Michael', 'Mary', 'Steven'], ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]



#### We want to get names of all the people with two or more A's 


In [3]:
new_names = []

for name_list in names:
    enough_as = [name for name in name_list if name.count("a")>=2]
    new_names.extend(enough_as)

print(new_names)

['Maria', 'Natalia']


#### WE want to write it in a single line !

In [4]:
result = [name for name_list in names for name in name_list if name.count("a") >= 2]
result

['Maria', 'Natalia']

# Functions

In [5]:
# normal functions 
def Add(x,y)-> int:
    return x+y

Add(4,5)

9

In [6]:
# functional Argument / Positional Arguments 

def my_function(x,y,z=1.5):
    if z > 1:
        return z*(x+y)
    else:
        return z/(x+y)


Scope 


In [7]:
a = []
def func(x):
    a.append(x)
    b=[]
    print(a)

func(3)

print(b)



[3]


NameError: name 'b' is not defined

In [8]:
def func1(x):
    global b
    b = []
    a.append(x)
    b.append(x*2)
    print(a)

func1(4)
print(b)

[3, 4]
[8]


In [9]:
def f():
    a= 1
    b=2
    c=3
    return a,b,c

ans = f()
print(ans)
print(type(ans))

(1, 2, 3)
<class 'tuple'>


In [10]:
def return_dic():
    a = 1
    b = 2
    c = 3
    return {
        "a" :a,
        "b" : b,
        "c" : c
    }

ans = return_dic()
print(ans)
print(type(ans))

{'a': 1, 'b': 2, 'c': 3}
<class 'dict'>


### Regular Expression


In [11]:
states=["  Alabama  ","Georgia!","georgia","Georgia","FlOrida",
       "south carolina##","West virginia?"]

import re  # regular expression 

def clean_string(strings):
    result = []

    for val in strings:
        val = val.strip() # used to remove leading and trailing spaces
        # print(val)
        val = re.sub("[!#?]","",val) # replacing expressions like !,#,? with ""
        # print(val)
        val = val.title()
        result.append(val)
    
    print(result)

clean_string(states)
    


['Alabama', 'Georgia', 'Georgia', 'Georgia', 'Florida', 'South Carolina', 'West Virginia']


#### lambda functions 

In [12]:
equvi = lambda x : x**2

equvi(10)

100

In [13]:
lambda_func = lambda x,y: x*y

lambda_func(8,2)

16

In [14]:
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

some_list = [1,2,3,4,5]
apply_to_list(some_list, lambda x : x*2)

[2, 4, 6, 8, 10]

In [15]:
names = ["Ansh", "Yash", "Daksh", "Chaahat"]
names.sort(key=lambda x:len(x))

print(names)

['Ansh', 'Yash', 'Daksh', 'Chaahat']


## Error and Exception Handling 

In [16]:
float("1.234")

1.234

In [17]:
def attempt_float(x):
    try:
        return float(x)
    except:
        return type(x)

attempt_float("Ansh")

str

# NUMPY


### Basic operations using numoy

In [2]:
import numpy as np

In [19]:
data = np.array([[1,2,3,4],[5,6,7,8]])
print(data)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
data.shape # prints .. rows, columns

(2, 4)

In [21]:
data.ndim # returns the number of dimensions here 2 

2

In [22]:
data*10 # saclar multiplication by 10 to each number in the data 


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [23]:
data = data+data
print(data)
data.dtype

[[ 2  4  6  8]
 [10 12 14 16]]


dtype('int64')

In [24]:
data1 = [6,7.5,8,0.1]
print(type(data1))

array = np.array(data1)
print(array)
print(type(array)) # this prints the type of the structure 
print(array.dtype) # this prints the value type of the number / entities inside structure

<class 'list'>
[6.  7.5 8.  0.1]
<class 'numpy.ndarray'>
float64


In [25]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int64)
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [28]:
# converting int to float 
arr = np.array([1,2,3,4])
print(arr)
float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
float64


In [29]:
arr = arr*arr
arr

array([ 1,  4,  9, 16])

In [30]:
print(arr-arr)

[0 0 0 0]


In [31]:
print(1/arr)

[1.         0.25       0.11111111 0.0625    ]


In [32]:
print(arr**2)

[  1  16  81 256]


In [33]:
arr2 = [[2,1,3,4]]
print(arr2 > arr)

[[ True False False False]]


In [34]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
# taking some part from the arr 
print(arr[2:5])

[2 3 4]


In [36]:
# creating a 2d array 
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(type(arr2d))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [37]:
print(arr2d[2,1])

8


In [38]:
arr2d[2:]

array([[7, 8, 9]])

In [39]:
print(arr2d)
arr2d[:2, 1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])

In [40]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### Transpose 


In [41]:
# Transpose 
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Dot product 


In [ ]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [43]:
arr.T@arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

# Pandas

In [1]:
import pandas as pd

In [45]:
df = pd.Series([1,2,3,4])
print(df)

0    1
1    2
2    3
3    4
dtype: int64


In [46]:
df = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
df2 = pd.Series([9,8,7,6], index=None)
print(df2)
print(df)

0    9
1    8
2    7
3    6
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [47]:
df.a

np.int64(1)

In [48]:
# small condition for having a pandas series 
print(df[df > 2])

c    3
d    4
e    5
dtype: int64


In [49]:
# converting dictionary to Pandas Series 
sdata={"Ohio":35000,"Texas":71000,"Oregon":16000,"Utah":5000}

obj3=pd.Series(sdata)
print(obj3)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64


#### Data Frame

In [50]:
data={"states":["Ohio","Ohio","Ohio","Nevada","Nevada","Nevada"],
      "year":[2000,2001,2002,2001,2002,2003],
      "pop":[1.5,1.7,3.6,2.4,2.9,3.2]
    }

frame=pd.DataFrame(data)
print(frame)

   states  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2


In [51]:
frame['debts'] = np.arange(6)
print(frame)


   states  year  pop  debts
0    Ohio  2000  1.5      0
1    Ohio  2001  1.7      1
2    Ohio  2002  3.6      2
3  Nevada  2001  2.4      3
4  Nevada  2002  2.9      4
5  Nevada  2003  3.2      5


In [52]:
frame['eastern'] = frame['states'] == "Ohio"
print(frame)

   states  year  pop  debts  eastern
0    Ohio  2000  1.5      0     True
1    Ohio  2001  1.7      1     True
2    Ohio  2002  3.6      2     True
3  Nevada  2001  2.4      3    False
4  Nevada  2002  2.9      4    False
5  Nevada  2003  3.2      5    False


In [53]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                 index=["Ohio","Colorado","Utah","New York"],
                 columns=["one","two","three","four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### loc

Label based indexing

In [54]:
data.loc['Ohio',['one','two']]

one    0
two    1
Name: Ohio, dtype: int64

#### iloc

index/number based indexing 

In [55]:
data.iloc[:2, :]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [56]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),
                  index=["three","one"],
                  columns=["d","a","b","c"])

frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [57]:
frame.sort_index

<bound method DataFrame.sort_index of        d  a  b  c
three  0  1  2  3
one    4  5  6  7>

In [58]:
#axis="columns" but these are arranged like row vise
frame.sort_index(axis="columns")

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [59]:
frame.describe()

d         a         b         c
count  2.000000  2.000000  2.000000  2.000000
mean   2.000000  3.000000  4.000000  5.000000
std    2.828427  2.828427  2.828427  2.828427
min    0.000000  1.000000  2.000000  3.000000
25%    1.000000  2.000000  3.000000  4.000000
50%    2.000000  3.000000  4.000000  5.000000
75%    3.000000  4.000000  5.000000  6.000000
max    4.000000  5.000000  6.000000  7.000000

### reading a file 

In [62]:
pd.read_csv("../data.csv")

32.502345269453031  31.70700584656992
0            53.426804          68.777596
1            61.530358          62.562382
2            47.475640          71.546632
3            59.813208          87.230925
4            55.142188          78.211518
..                 ...                ...
94           50.030174          81.536991
95           49.239765          72.111832
96           50.039576          85.232007
97           48.149859          66.224958
98           25.128485          53.454394

[99 rows x 2 columns]

In [69]:
df_temp = pd.DataFrame(np.arange(12).reshape(3,4), index=[0,1,2], columns=["Zero","One", "Two", "Three"])
print(df_temp)

   Zero  One  Two  Three
0     0    1    2      3
1     4    5    6      7
2     8    9   10     11


In [ ]:
# this creates a csv file.
df_temp.to_csv("created.csv")

## DATA CLEANING AND PREPARATION

In [6]:
## loading the data first ... 
df = pd.read_csv('created.csv')
print(df.columns)
print(df)

Index(['0', 'Zero', 'One', 'Two', 'Three'], dtype='object')
   0  Zero  One  Two  Three
0  0     0    1    2      3
1  1     4    5    6      7
2  2     8    9   10     11


In [8]:
float_data = pd.Series([1.2,-3.5,np.nan, 0]);
float_data.isna().sum()

np.int64(1)

In [10]:
data=pd.DataFrame([[1.,6.5,3.],[1.,np.nan,np.nan],
                  [np.nan,np.nan,np.nan],[np.nan,6.5,3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

#### Dropping the Cols 


In [16]:
# here is any particular row,col is NaN then in that case whole row is dropped !
data.dropna()

# here if only whole row is NaN in that case only the whole row is dropped !
data.dropna(how="all")

# dropping the col's instead of rows && how="all" specifies that if the while col is Nan in that case only we drop
data.dropna(axis="columns", how="all")



0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
df = pd.DataFrame(np.random.standard_normal((7,3)))
df.iloc[:4,1] = np.nan
df.iloc[:2,2] = np.nan
df

0         1         2
0  0.698617       NaN       NaN
1  0.299929       NaN       NaN
2  0.882003       NaN  0.780388
3 -0.296464       NaN  0.025227
4  0.569345 -0.178700 -0.393506
5 -0.449529 -1.341606 -1.744743
6 -1.947398  0.322508  0.255398

In [ ]:
# droping rows / cols only if below a specific threshold 

# thres specifies how many minimum non NaN rows are needed .. like suppose thresh is like 3 then that all the rows having more less than 3 non NaN are droped 
df.dropna(thresh=2)

# here axis = 1 specifies that rather than looking and deleting for rows .. we look for cols and delete them 
df.dropna(thresh=4, axis=1)

0         2
0  0.698617       NaN
1  0.299929       NaN
2  0.882003  0.780388
3 -0.296464  0.025227
4  0.569345 -0.393506
5 -0.449529 -1.744743
6 -1.947398  0.255398

### Flling with Missing Values 

In [30]:
df

0         1         2
0  0.698617       NaN       NaN
1  0.299929       NaN       NaN
2  0.882003       NaN  0.780388
3 -0.296464       NaN  0.025227
4  0.569345 -0.178700 -0.393506
5 -0.449529 -1.341606 -1.744743
6 -1.947398  0.322508  0.255398

In [31]:
df.fillna(0)

0         1         2
0  0.698617  0.000000  0.000000
1  0.299929  0.000000  0.000000
2  0.882003  0.000000  0.780388
3 -0.296464  0.000000  0.025227
4  0.569345 -0.178700 -0.393506
5 -0.449529 -1.341606 -1.744743
6 -1.947398  0.322508  0.255398

In [ ]:
# here we specify that we want to fill the col 1 with 0.5 and col 2 as 0.9 if there is NaN
df.fillna({1:0.5, 2:0.9})

0         1         2
0  0.698617  0.500000  0.900000
1  0.299929  0.500000  0.900000
2  0.882003  0.500000  0.780388
3 -0.296464  0.500000  0.025227
4  0.569345 -0.178700 -0.393506
5 -0.449529 -1.341606 -1.744743
6 -1.947398  0.322508  0.255398

##### ffill -> Forward Fill if a technique we use to fill the missing values and put 

In [ ]:
# here we are trying to forward fill it the missing values using forward fill (ffill) but since there is no numbers before the NaN hence forward fill fails 
df.ffill()

0         1         2
0  0.698617       NaN       NaN
1  0.299929       NaN       NaN
2  0.882003       NaN  0.780388
3 -0.296464       NaN  0.025227
4  0.569345 -0.178700 -0.393506
5 -0.449529 -1.341606 -1.744743
6 -1.947398  0.322508  0.255398

In [46]:
df = pd.DataFrame(np.random.standard_normal((7,3)))
df.iloc[3:, 2] = np.nan
df.iloc[4:, 0:2] = np.nan
print(df)
df.ffill()

          0         1         2
0 -0.644748  0.786536  1.045882
1 -1.356468  0.746164  0.580289
2 -0.553745  0.364244 -1.110547
3  1.394042 -1.049290       NaN
4       NaN       NaN       NaN
5       NaN       NaN       NaN
6       NaN       NaN       NaN


0         1         2
0 -0.644748  0.786536  1.045882
1 -1.356468  0.746164  0.580289
2 -0.553745  0.364244 -1.110547
3  1.394042 -1.049290 -1.110547
4  1.394042 -1.049290 -1.110547
5  1.394042 -1.049290 -1.110547
6  1.394042 -1.049290 -1.110547