# NUMPY


### Basic operations using numoy

In [ ]:
import numpy as np

In [ ]:
data = np.array([[1,2,3,4],[5,6,7,8]])
print(data)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
data.shape # prints .. rows, columns

(2, 4)

In [ ]:
data.ndim # returns the number of dimensions here 2 

2

In [ ]:
data*10 # saclar multiplication by 10 to each number in the data 


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
data = data+data
print(data)
data.dtype

[[ 2  4  6  8]
 [10 12 14 16]]


dtype('int64')

In [ ]:
data1 = [6,7.5,8,0.1]
print(type(data1))

array = np.array(data1)
print(array)
print(type(array)) # this prints the type of the structure 
print(array.dtype) # this prints the value type of the number / entities inside structure

<class 'list'>
[6.  7.5 8.  0.1]
<class 'numpy.ndarray'>
float64


In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int64)
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [ ]:
# converting int to float 
arr = np.array([1,2,3,4])
print(arr)
float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
float64


In [ ]:
arr = arr*arr
arr

array([ 1,  4,  9, 16])

In [ ]:
print(arr-arr)

[0 0 0 0]


In [ ]:
print(1/arr)

[1.         0.25       0.11111111 0.0625    ]


In [ ]:
print(arr**2)

[  1  16  81 256]


In [ ]:
arr2 = [[2,1,3,4]]
print(arr2 > arr)

[[ True False False False]]


In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# taking some part from the arr 
print(arr[2:5])

[2 3 4]


In [ ]:
# creating a 2d array 
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(type(arr2d))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [ ]:
print(arr2d[2,1])

8


In [ ]:
arr2d[2:]

array([[7, 8, 9]])

In [ ]:
print(arr2d)
arr2d[:2, 1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])

In [ ]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### Transpose 


In [ ]:
# Transpose 
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Dot product 


In [ ]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [ ]:
arr.T@arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])